services:
  israeli-banks-actual-budget-importer:
    image: tomerh2001/israeli-banks-actual-budget-importer:latest
    container_name: israeli-banks-actual-budget-importer
    cap_add:
      - SYS_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/app/config.json
      - ./cache:/app/cache
      - ./chrome-data:/app/chrome-data
