name: Semantic Versioning

on:
  push:
    branches:
      - main 
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
    
    - name: Install Dependencies
      run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Make repo writable for BuildKit
      run: sudo chmod -R 777 $GITHUB_WORKSPACE/.yarn

    - name: Semantic Release
      run: yarn semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_REPO: ${{ github.server_url }}/${{ github.repository }}
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
